name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: |
            node_modules
            usr/**/node_modules
          key: ${{ runner.os }}-node_modules-${{hashFiles('**/package.json')}}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Build
        run: |
          npm ci
          npm run build

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
          scope: "@Gnarus-G"
          
      - name: Publish
        run: npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.PKG_AUTH_TOKEN}}
